### ISSUE TITLE
Remove "seq" from Command data structure

### ISSUE THREAD

**Issue by jupitermoon23** [diva-exchange/divachain#9]
transaction.ts:

```
interface Cmd {
  seq: number;
  command: string;
}
```
It's not clear what this "sequence" is useful for. The commands are sorted within a transaction and the sort order (sequence) of the commands is given by the fact that the signature of a transaction would change, if the sequence of the commands would change.

**Comment by diva-exchange** [comment]
solved on branch develop-tx
